name: infra-apply

on:
  push:
    branches:
      - main
    paths:
      - 'DevInfraTargetPath/terraform/**'
      - '.github/workflows/**'

env:
  TF_STATE_BUCKET: "stackgen-meetup-terraform-state"
  AWS_REGION: "us-west-2"

jobs:
  apply-appstack:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::222634395437:role/sep-24-meetup-oidc-github

      - name: Apply TF Changes
        uses: ./.github/workflows/apply
        with:
          tf_state_bucket: ${{ env.TF_STATE_BUCKET }}
          tf_state_key: ${{ github.repository }}/terraform.tfstate
          aws_region: ${{ env.AWS_REGION }}
